// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.20.1-devel
// 	protoc        v3.11.4
// source: phadl/testunion/union.adl

package testunion

import (
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ADLSumType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Union:
	//	*ADLSumType_A
	//	*ADLSumType_B
	//	*ADLSumType_X
	//	*ADLSumType_Y
	//	*ADLSumType_Z
	Union isADLSumType_Union `protobuf_oneof:"union"`
}

func (x *ADLSumType) Reset() {
	*x = ADLSumType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_phadl_testunion_union_adl_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ADLSumType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ADLSumType) ProtoMessage() {}

func (x *ADLSumType) ProtoReflect() protoreflect.Message {
	mi := &file_phadl_testunion_union_adl_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ADLSumType.ProtoReflect.Descriptor instead.
func (*ADLSumType) Descriptor() ([]byte, []int) {
	return file_phadl_testunion_union_adl_rawDescGZIP(), []int{0}
}

func (m *ADLSumType) GetUnion() isADLSumType_Union {
	if m != nil {
		return m.Union
	}
	return nil
}

func (x *ADLSumType) GetA() string {
	if x, ok := x.GetUnion().(*ADLSumType_A); ok {
		return x.A
	}
	return ""
}

func (x *ADLSumType) GetB() string {
	if x, ok := x.GetUnion().(*ADLSumType_B); ok {
		return x.B
	}
	return ""
}

func (x *ADLSumType) GetX() int64 {
	if x, ok := x.GetUnion().(*ADLSumType_X); ok {
		return x.X
	}
	return 0
}

func (x *ADLSumType) GetY() int64 {
	if x, ok := x.GetUnion().(*ADLSumType_Y); ok {
		return x.Y
	}
	return 0
}

func (x *ADLSumType) GetZ() *empty.Empty {
	if x, ok := x.GetUnion().(*ADLSumType_Z); ok {
		return x.Z
	}
	return nil
}

type isADLSumType_Union interface {
	isADLSumType_Union()
}

type ADLSumType_A struct {
	A string `protobuf:"bytes,1,opt,name=A,proto3,oneof"`
}

type ADLSumType_B struct {
	B string `protobuf:"bytes,2,opt,name=B,proto3,oneof"`
}

type ADLSumType_X struct {
	X int64 `protobuf:"zigzag64,3,opt,name=X,proto3,oneof"`
}

type ADLSumType_Y struct {
	Y int64 `protobuf:"zigzag64,4,opt,name=Y,proto3,oneof"`
}

type ADLSumType_Z struct {
	Z *empty.Empty `protobuf:"bytes,5,opt,name=Z,proto3,oneof"`
}

func (*ADLSumType_A) isADLSumType_Union() {}

func (*ADLSumType_B) isADLSumType_Union() {}

func (*ADLSumType_X) isADLSumType_Union() {}

func (*ADLSumType_Y) isADLSumType_Union() {}

func (*ADLSumType_Z) isADLSumType_Union() {}

var File_phadl_testunion_union_adl protoreflect.FileDescriptor

var file_phadl_testunion_union_adl_rawDesc = []byte{
	0x0a, 0x19, 0x70, 0x68, 0x61, 0x64, 0x6c, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x75, 0x6e, 0x69, 0x6f,
	0x6e, 0x2f, 0x75, 0x6e, 0x69, 0x6f, 0x6e, 0x2e, 0x61, 0x64, 0x6c, 0x12, 0x0f, 0x70, 0x68, 0x61,
	0x64, 0x6c, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x75, 0x6e, 0x69, 0x6f, 0x6e, 0x1a, 0x1b, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d,
	0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x7d, 0x0a, 0x0a, 0x41, 0x44, 0x4c,
	0x53, 0x75, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0e, 0x0a, 0x01, 0x41, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x48, 0x00, 0x52, 0x01, 0x41, 0x12, 0x0e, 0x0a, 0x01, 0x42, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x48, 0x00, 0x52, 0x01, 0x42, 0x12, 0x0e, 0x0a, 0x01, 0x58, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x12, 0x48, 0x00, 0x52, 0x01, 0x58, 0x12, 0x0e, 0x0a, 0x01, 0x59, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x12, 0x48, 0x00, 0x52, 0x01, 0x59, 0x12, 0x26, 0x0a, 0x01, 0x5a, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x48, 0x00, 0x52, 0x01, 0x5a, 0x42,
	0x07, 0x0a, 0x05, 0x75, 0x6e, 0x69, 0x6f, 0x6e, 0x42, 0x35, 0x5a, 0x33, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x69, 0x6c, 0x6c, 0x65, 0x72, 0x67, 0x61, 0x72,
	0x79, 0x6d, 0x2f, 0x70, 0x62, 0x61, 0x64, 0x6c, 0x2f, 0x70, 0x62, 0x2d, 0x67, 0x65, 0x6e, 0x2f,
	0x70, 0x68, 0x61, 0x64, 0x6c, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x75, 0x6e, 0x69, 0x6f, 0x6e, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_phadl_testunion_union_adl_rawDescOnce sync.Once
	file_phadl_testunion_union_adl_rawDescData = file_phadl_testunion_union_adl_rawDesc
)

func file_phadl_testunion_union_adl_rawDescGZIP() []byte {
	file_phadl_testunion_union_adl_rawDescOnce.Do(func() {
		file_phadl_testunion_union_adl_rawDescData = protoimpl.X.CompressGZIP(file_phadl_testunion_union_adl_rawDescData)
	})
	return file_phadl_testunion_union_adl_rawDescData
}

var file_phadl_testunion_union_adl_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_phadl_testunion_union_adl_goTypes = []interface{}{
	(*ADLSumType)(nil),  // 0: phadl.testunion.ADLSumType
	(*empty.Empty)(nil), // 1: google.protobuf.Empty
}
var file_phadl_testunion_union_adl_depIdxs = []int32{
	1, // 0: phadl.testunion.ADLSumType.Z:type_name -> google.protobuf.Empty
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_phadl_testunion_union_adl_init() }
func file_phadl_testunion_union_adl_init() {
	if File_phadl_testunion_union_adl != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_phadl_testunion_union_adl_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ADLSumType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_phadl_testunion_union_adl_msgTypes[0].OneofWrappers = []interface{}{
		(*ADLSumType_A)(nil),
		(*ADLSumType_B)(nil),
		(*ADLSumType_X)(nil),
		(*ADLSumType_Y)(nil),
		(*ADLSumType_Z)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_phadl_testunion_union_adl_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_phadl_testunion_union_adl_goTypes,
		DependencyIndexes: file_phadl_testunion_union_adl_depIdxs,
		MessageInfos:      file_phadl_testunion_union_adl_msgTypes,
	}.Build()
	File_phadl_testunion_union_adl = out.File
	file_phadl_testunion_union_adl_rawDesc = nil
	file_phadl_testunion_union_adl_goTypes = nil
	file_phadl_testunion_union_adl_depIdxs = nil
}
