// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.20.1-devel
// 	protoc        v3.11.4
// source: teststruct/struct.adl

package teststruct

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ADLProductType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	A string `protobuf:"bytes,1,opt,name=A,proto3" json:"A,omitempty"`
	B string `protobuf:"bytes,2,opt,name=B,proto3" json:"B,omitempty"`
	X int64  `protobuf:"zigzag64,3,opt,name=X,proto3" json:"X,omitempty"`
	Y int64  `protobuf:"zigzag64,4,opt,name=Y,proto3" json:"Y,omitempty"`
}

func (x *ADLProductType) Reset() {
	*x = ADLProductType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_teststruct_struct_adl_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ADLProductType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ADLProductType) ProtoMessage() {}

func (x *ADLProductType) ProtoReflect() protoreflect.Message {
	mi := &file_teststruct_struct_adl_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ADLProductType.ProtoReflect.Descriptor instead.
func (*ADLProductType) Descriptor() ([]byte, []int) {
	return file_teststruct_struct_adl_rawDescGZIP(), []int{0}
}

func (x *ADLProductType) GetA() string {
	if x != nil {
		return x.A
	}
	return ""
}

func (x *ADLProductType) GetB() string {
	if x != nil {
		return x.B
	}
	return ""
}

func (x *ADLProductType) GetX() int64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *ADLProductType) GetY() int64 {
	if x != nil {
		return x.Y
	}
	return 0
}

var File_teststruct_struct_adl protoreflect.FileDescriptor

var file_teststruct_struct_adl_rawDesc = []byte{
	0x0a, 0x15, 0x74, 0x65, 0x73, 0x74, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x2f, 0x73, 0x74, 0x72,
	0x75, 0x63, 0x74, 0x2e, 0x61, 0x64, 0x6c, 0x12, 0x0a, 0x74, 0x65, 0x73, 0x74, 0x73, 0x74, 0x72,
	0x75, 0x63, 0x74, 0x22, 0x48, 0x0a, 0x0e, 0x41, 0x44, 0x4c, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0c, 0x0a, 0x01, 0x41, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x01, 0x41, 0x12, 0x0c, 0x0a, 0x01, 0x42, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x01,
	0x42, 0x12, 0x0c, 0x0a, 0x01, 0x58, 0x18, 0x03, 0x20, 0x01, 0x28, 0x12, 0x52, 0x01, 0x58, 0x12,
	0x0c, 0x0a, 0x01, 0x59, 0x18, 0x04, 0x20, 0x01, 0x28, 0x12, 0x52, 0x01, 0x59, 0x42, 0x30, 0x5a,
	0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x69, 0x6c, 0x6c,
	0x65, 0x72, 0x67, 0x61, 0x72, 0x79, 0x6d, 0x2f, 0x70, 0x62, 0x61, 0x64, 0x6c, 0x2f, 0x70, 0x62,
	0x2d, 0x67, 0x65, 0x6e, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_teststruct_struct_adl_rawDescOnce sync.Once
	file_teststruct_struct_adl_rawDescData = file_teststruct_struct_adl_rawDesc
)

func file_teststruct_struct_adl_rawDescGZIP() []byte {
	file_teststruct_struct_adl_rawDescOnce.Do(func() {
		file_teststruct_struct_adl_rawDescData = protoimpl.X.CompressGZIP(file_teststruct_struct_adl_rawDescData)
	})
	return file_teststruct_struct_adl_rawDescData
}

var file_teststruct_struct_adl_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_teststruct_struct_adl_goTypes = []interface{}{
	(*ADLProductType)(nil), // 0: teststruct.ADLProductType
}
var file_teststruct_struct_adl_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_teststruct_struct_adl_init() }
func file_teststruct_struct_adl_init() {
	if File_teststruct_struct_adl != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_teststruct_struct_adl_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ADLProductType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_teststruct_struct_adl_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_teststruct_struct_adl_goTypes,
		DependencyIndexes: file_teststruct_struct_adl_depIdxs,
		MessageInfos:      file_teststruct_struct_adl_msgTypes,
	}.Build()
	File_teststruct_struct_adl = out.File
	file_teststruct_struct_adl_rawDesc = nil
	file_teststruct_struct_adl_goTypes = nil
	file_teststruct_struct_adl_depIdxs = nil
}
