// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.20.1-devel
// 	protoc        v3.11.4
// source: testunion/union.proto

package testunion

import (
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type SumType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Union:
	//	*SumType_A
	//	*SumType_B
	//	*SumType_X
	//	*SumType_Y
	//	*SumType_Z
	Union isSumType_Union `protobuf_oneof:"union"`
}

func (x *SumType) Reset() {
	*x = SumType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_testunion_union_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SumType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SumType) ProtoMessage() {}

func (x *SumType) ProtoReflect() protoreflect.Message {
	mi := &file_testunion_union_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SumType.ProtoReflect.Descriptor instead.
func (*SumType) Descriptor() ([]byte, []int) {
	return file_testunion_union_proto_rawDescGZIP(), []int{0}
}

func (m *SumType) GetUnion() isSumType_Union {
	if m != nil {
		return m.Union
	}
	return nil
}

func (x *SumType) GetA() string {
	if x, ok := x.GetUnion().(*SumType_A); ok {
		return x.A
	}
	return ""
}

func (x *SumType) GetB() string {
	if x, ok := x.GetUnion().(*SumType_B); ok {
		return x.B
	}
	return ""
}

func (x *SumType) GetX() int64 {
	if x, ok := x.GetUnion().(*SumType_X); ok {
		return x.X
	}
	return 0
}

func (x *SumType) GetY() int64 {
	if x, ok := x.GetUnion().(*SumType_Y); ok {
		return x.Y
	}
	return 0
}

func (x *SumType) GetZ() *empty.Empty {
	if x, ok := x.GetUnion().(*SumType_Z); ok {
		return x.Z
	}
	return nil
}

type isSumType_Union interface {
	isSumType_Union()
}

type SumType_A struct {
	A string `protobuf:"bytes,1,opt,name=A,proto3,oneof"`
}

type SumType_B struct {
	B string `protobuf:"bytes,2,opt,name=B,proto3,oneof"`
}

type SumType_X struct {
	X int64 `protobuf:"varint,3,opt,name=X,proto3,oneof"`
}

type SumType_Y struct {
	Y int64 `protobuf:"zigzag64,4,opt,name=Y,proto3,oneof"`
}

type SumType_Z struct {
	Z *empty.Empty `protobuf:"bytes,5,opt,name=Z,proto3,oneof"`
}

func (*SumType_A) isSumType_Union() {}

func (*SumType_B) isSumType_Union() {}

func (*SumType_X) isSumType_Union() {}

func (*SumType_Y) isSumType_Union() {}

func (*SumType_Z) isSumType_Union() {}

type ProductType1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	S *SumType `protobuf:"bytes,1,opt,name=S,proto3" json:"S,omitempty"`
}

func (x *ProductType1) Reset() {
	*x = ProductType1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_testunion_union_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProductType1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductType1) ProtoMessage() {}

func (x *ProductType1) ProtoReflect() protoreflect.Message {
	mi := &file_testunion_union_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductType1.ProtoReflect.Descriptor instead.
func (*ProductType1) Descriptor() ([]byte, []int) {
	return file_testunion_union_proto_rawDescGZIP(), []int{1}
}

func (x *ProductType1) GetS() *SumType {
	if x != nil {
		return x.S
	}
	return nil
}

type ProductType2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	S *SumType `protobuf:"bytes,1,opt,name=S,proto3" json:"S,omitempty"`
	T *SumType `protobuf:"bytes,2,opt,name=T,proto3" json:"T,omitempty"`
}

func (x *ProductType2) Reset() {
	*x = ProductType2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_testunion_union_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProductType2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductType2) ProtoMessage() {}

func (x *ProductType2) ProtoReflect() protoreflect.Message {
	mi := &file_testunion_union_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductType2.ProtoReflect.Descriptor instead.
func (*ProductType2) Descriptor() ([]byte, []int) {
	return file_testunion_union_proto_rawDescGZIP(), []int{2}
}

func (x *ProductType2) GetS() *SumType {
	if x != nil {
		return x.S
	}
	return nil
}

func (x *ProductType2) GetT() *SumType {
	if x != nil {
		return x.T
	}
	return nil
}

var File_testunion_union_proto protoreflect.FileDescriptor

var file_testunion_union_proto_rawDesc = []byte{
	0x0a, 0x15, 0x74, 0x65, 0x73, 0x74, 0x75, 0x6e, 0x69, 0x6f, 0x6e, 0x2f, 0x75, 0x6e, 0x69, 0x6f,
	0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x74, 0x65, 0x73, 0x74, 0x75, 0x6e, 0x69,
	0x6f, 0x6e, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x7a, 0x0a, 0x07, 0x53, 0x75, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0e, 0x0a, 0x01, 0x41, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x01, 0x41, 0x12, 0x0e, 0x0a, 0x01, 0x42, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x01, 0x42, 0x12, 0x0e, 0x0a, 0x01, 0x58, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x03, 0x48, 0x00, 0x52, 0x01, 0x58, 0x12, 0x0e, 0x0a, 0x01, 0x59, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x12, 0x48, 0x00, 0x52, 0x01, 0x59, 0x12, 0x26, 0x0a, 0x01, 0x5a, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x48, 0x00, 0x52,
	0x01, 0x5a, 0x42, 0x07, 0x0a, 0x05, 0x75, 0x6e, 0x69, 0x6f, 0x6e, 0x22, 0x30, 0x0a, 0x0c, 0x50,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x54, 0x79, 0x70, 0x65, 0x31, 0x12, 0x20, 0x0a, 0x01, 0x53,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x75, 0x6e, 0x69,
	0x6f, 0x6e, 0x2e, 0x53, 0x75, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x52, 0x01, 0x53, 0x22, 0x52, 0x0a,
	0x0c, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x54, 0x79, 0x70, 0x65, 0x32, 0x12, 0x20, 0x0a,
	0x01, 0x53, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x75,
	0x6e, 0x69, 0x6f, 0x6e, 0x2e, 0x53, 0x75, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x52, 0x01, 0x53, 0x12,
	0x20, 0x0a, 0x01, 0x54, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x74, 0x65, 0x73,
	0x74, 0x75, 0x6e, 0x69, 0x6f, 0x6e, 0x2e, 0x53, 0x75, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x52, 0x01,
	0x54, 0x42, 0x2f, 0x5a, 0x2d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x6d, 0x69, 0x6c, 0x6c, 0x65, 0x72, 0x67, 0x61, 0x72, 0x79, 0x6d, 0x2f, 0x70, 0x62, 0x61, 0x64,
	0x6c, 0x2f, 0x70, 0x62, 0x2d, 0x67, 0x65, 0x6e, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x75, 0x6e, 0x69,
	0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_testunion_union_proto_rawDescOnce sync.Once
	file_testunion_union_proto_rawDescData = file_testunion_union_proto_rawDesc
)

func file_testunion_union_proto_rawDescGZIP() []byte {
	file_testunion_union_proto_rawDescOnce.Do(func() {
		file_testunion_union_proto_rawDescData = protoimpl.X.CompressGZIP(file_testunion_union_proto_rawDescData)
	})
	return file_testunion_union_proto_rawDescData
}

var file_testunion_union_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_testunion_union_proto_goTypes = []interface{}{
	(*SumType)(nil),      // 0: testunion.SumType
	(*ProductType1)(nil), // 1: testunion.ProductType1
	(*ProductType2)(nil), // 2: testunion.ProductType2
	(*empty.Empty)(nil),  // 3: google.protobuf.Empty
}
var file_testunion_union_proto_depIdxs = []int32{
	3, // 0: testunion.SumType.Z:type_name -> google.protobuf.Empty
	0, // 1: testunion.ProductType1.S:type_name -> testunion.SumType
	0, // 2: testunion.ProductType2.S:type_name -> testunion.SumType
	0, // 3: testunion.ProductType2.T:type_name -> testunion.SumType
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_testunion_union_proto_init() }
func file_testunion_union_proto_init() {
	if File_testunion_union_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_testunion_union_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SumType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_testunion_union_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProductType1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_testunion_union_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProductType2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_testunion_union_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*SumType_A)(nil),
		(*SumType_B)(nil),
		(*SumType_X)(nil),
		(*SumType_Y)(nil),
		(*SumType_Z)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_testunion_union_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_testunion_union_proto_goTypes,
		DependencyIndexes: file_testunion_union_proto_depIdxs,
		MessageInfos:      file_testunion_union_proto_msgTypes,
	}.Build()
	File_testunion_union_proto = out.File
	file_testunion_union_proto_rawDesc = nil
	file_testunion_union_proto_goTypes = nil
	file_testunion_union_proto_depIdxs = nil
}
